### PR TITLE
Create messages-pl.yml

### PR DESCRIPTION
**Pull request by piesio98**

### CODE REVIEW

**Comment by kamil7430** [comment]
Hey

**Comment by kamil7430** [comment]
Where I can upload Polish translation?

**Comment by daboross** [comment]
You can do it like you did.

The file you uploaded only has the text `ss` in it, and not any translations. Try doing it again, putting the translations string in the file text?

**Comment by kamil7430** [comment]
I upload this file on http://tny.cz/16c6297f

**Comment by daboross** [comment]
Thank you, I've added the translation!

**Comment by kamil7430** [comment]
Hey, I'm kamil7430, add ME as translator. Ok?

**Comment by daboross** [comment]
@kamil7430 I'm not entirely sure that the translator group in github still exists. Where do you mean?

**Comment by kamil7430** [comment]
Why my translation doesn't working?

**Comment by daboross** [comment]
it is in the development version now, but not in the released version yet. If you want to use it on your server now, you can copy and paste all of the lines from the file you made into the `plugins/SkyWars/messages.yml` file.

**Pull request closed without merging**
